#!/bin/bash

echo "=== Debug Derma Stamp Filtering Issue ==="
echo ""
echo "The derma stamp evening routine step is showing up on:"
echo "✅ Dashboard"
echo "✅ Routine tab - Weekly"
echo "❌ Routine tab - Evening"
echo ""
echo "🔍 DEBUGGING STEPS:"
echo ""
echo "1. Check the derma stamp step's properties:"
echo "   - What is the 'period' property set to?"
echo "   - What is the 'time' property set to?"
echo "   - What is the 'frequency' property set to?"
echo ""
echo "2. Check the inferPeriod function logic:"
echo "   - If frequency contains 'weekly' → returns 'weekly'"
echo "   - If time contains 'am' → returns 'morning'"
echo "   - Otherwise → returns 'evening'"
echo ""
echo "3. Check the stepsByPeriod filtering:"
echo "   - Filters by: s.period === p OR inferPeriod(s) === p"
echo "   - For evening tab: looks for period='evening' OR inferPeriod='evening'"
echo ""
echo "4. Check the daily tab filtering in RoutineScreen:"
echo "   - Additional filter: step.days.includes(todayDayOfWeek)"
echo "   - This might be filtering out the derma stamp"
echo ""
echo "🎯 LIKELY CAUSES:"
echo ""
echo "A) Period inference issue:"
echo "   - Derma stamp might have time='PM' or 'evening' but inferPeriod is returning 'weekly'"
echo "   - Or period is explicitly set to 'weekly' instead of 'evening'"
echo ""
echo "B) Days filtering issue:"
echo "   - Derma stamp might not have the correct days array"
echo "   - Or today's day of week is not in the days array"
echo ""
echo "C) Time format issue:"
echo "   - Time might be in wrong format (e.g., 'PM' vs 'pm')"
echo ""
echo "🧪 TO DEBUG:"
echo ""
echo "1. Go to the routine screen"
echo "2. Check what the derma stamp step object looks like"
echo "3. Verify:"
echo "   - step.period value"
echo "   - step.time value" 
echo "   - step.days array"
echo "   - step.frequency value"
echo "4. Check what inferPeriod(step) returns"
echo "5. Check what today's day of week is"
echo ""
echo "Press Enter when you've gathered this info..."
read -r

echo "Please share the derma stamp step object properties so I can identify the exact issue!"
