#!/bin/bash

echo "=== Debugging Edge Function Issue ==="
echo ""
echo "🚨 CURRENT ERROR: null value in column \"id\" of relation \"profiles\" violates not-null constraint"
echo ""
echo "This means the edge function is trying to insert a profile without an 'id' value."
echo "But looking at the code, it should be inserting 'id: userId'."
echo ""
echo "🔍 POSSIBLE CAUSES:"
echo "1. Edge function hasn't been deployed with the latest changes"
echo "2. Database table structure doesn't match what edge function expects"
echo "3. Edge function is using cached/old version"
echo ""
echo "🔧 DEBUGGING STEPS:"
echo ""
echo "STEP 1: Check Database Structure"
echo "1. Go to Supabase SQL Editor"
echo "2. Run the queries in test_edge_function.sql"
echo "3. This will show you the current table structure and test a manual insert"
echo ""
echo "STEP 2: Check Edge Function"
echo "1. Go to Supabase Dashboard → Edge Functions"
echo "2. Find the 'create-guest' function"
echo "3. Check if the code shows:"
echo "   const { error: pErr } = await supa.from('profiles').insert({"
echo "     id: userId,"
echo "     email,"
echo "     is_guest: true,"
echo "   })"
echo ""
echo "STEP 3: Deploy Edge Function"
echo "If the code is correct but not deployed:"
echo "1. Copy the updated code from supabase/functions/create-guest/index.ts"
echo "2. Paste it into the Supabase Dashboard Edge Function editor"
echo "3. Deploy the function"
echo ""
echo "STEP 4: Test Again"
echo "1. Try creating a guest user in your app"
echo "2. Check if the error is resolved"
echo ""
echo "Press Enter to continue..."
read -r

echo "✅ The issue is likely that the edge function changes haven't been deployed yet."
echo "Check the database structure first, then deploy the updated edge function."
