#!/bin/bash

echo "=== Debugging Database Mismatch ==="
echo ""
echo "🔍 If the edge function is deployed but still failing, the issue is:"
echo "   The database table structure doesn't match what the edge function expects"
echo ""
echo "🚨 CURRENT ERROR: null value in column \"id\" of relation \"profiles\" violates not-null constraint"
echo ""
echo "This means:"
echo "1. ✅ Edge function is trying to insert: { id: userId, email, is_guest: true }"
echo "2. ❌ Database is rejecting the insert because 'id' is null"
echo "3. 🤔 But userId should not be null..."
echo ""
echo "🔧 POSSIBLE CAUSES:"
echo "1. The 'id' column in profiles table has a constraint that's blocking the insert"
echo "2. The 'id' column doesn't exist or has wrong data type"
echo "3. There's a foreign key constraint issue"
echo "4. The userId from auth.admin.createUser is actually null"
echo ""
echo "🔍 DEBUGGING STEPS:"
echo ""
echo "STEP 1: Check Database Structure"
echo "1. Go to Supabase SQL Editor"
echo "2. Run the queries in database/check_profiles_table_exact.sql"
echo "3. This will show you the exact table structure and constraints"
echo ""
echo "STEP 2: Check Edge Function Logs"
echo "1. Go to Supabase Dashboard → Edge Functions → create-guest"
echo "2. Check the logs to see what userId value is being generated"
echo "3. Look for any errors in the auth.admin.createUser call"
echo ""
echo "STEP 3: Test Manual Insert"
echo "If the table structure looks correct, try a manual insert:"
echo "INSERT INTO profiles (id, email, is_guest) VALUES ('test-uuid', 'test@test.com', true);"
echo ""
echo "STEP 4: Check Auth Users"
echo "Run: SELECT * FROM auth.users LIMIT 5;"
echo "This will show if users are being created properly"
echo ""
echo "Press Enter to continue..."
read -r

echo "✅ The issue is likely a database constraint or the userId is actually null."
echo "Run the diagnostic queries to see exactly what's in your database."
