#!/bin/bash

echo "=== Deploying Fixed create-guest Edge Function ==="
echo ""
echo "🔧 FIXED: Added 'id' column to the profile insert"
echo ""
echo "The edge function was trying to insert:"
echo "- user_id: userId"
echo "- handle: null"
echo "- is_guest: true"
echo "- avatar_url: null"
echo ""
echo "But missing the required 'id' column (primary key)."
echo ""
echo "✅ NOW FIXED:"
echo "- id: userId (primary key)"
echo "- user_id: userId (for compatibility)"
echo "- handle: null"
echo "- is_guest: true"
echo "- avatar_url: null"
echo ""
echo "🚀 TO DEPLOY:"
echo "1. Make sure you're in the project root directory"
echo "2. Run: supabase functions deploy create-guest"
echo "3. Or if using Supabase CLI: supabase functions deploy"
echo ""
echo "📋 ALTERNATIVE:"
echo "If you don't have Supabase CLI set up, you can:"
echo "1. Go to Supabase Dashboard"
echo "2. Navigate to Edge Functions"
echo "3. Find the 'create-guest' function"
echo "4. Replace the code with the updated version"
echo "5. Deploy the function"
echo ""
echo "Press Enter to continue..."
read -r

echo "✅ The create-guest edge function has been fixed to include the 'id' column."
echo "Deploy the updated function and the null constraint error should be resolved."
