#!/bin/bash

echo "=== Fixing Profiles Table Schema Cache Issue ==="
echo ""
echo "🚨 ERROR: 'could not find the id column of profiles in the schema cache'"
echo ""
echo "This error indicates the profiles table structure is corrupted or"
echo "the schema cache is out of sync. Here are the steps to fix it:"
echo ""
echo "🔍 STEP 1: DIAGNOSE THE ISSUE"
echo "1. Go to Supabase SQL Editor"
echo "2. Run the queries in database/diagnose_profiles_table.sql"
echo "3. Check if the profiles table has proper structure"
echo ""
echo "🔧 STEP 2: FIX THE TABLE"
echo "Choose one of these options:"
echo ""
echo "OPTION A: Refresh Schema Cache (Try this first)"
echo "1. Go to Supabase Dashboard"
echo "2. Navigate to Database > Tables"
echo "3. Find the 'profiles' table"
echo "4. Click the refresh button or restart your Supabase project"
echo ""
echo "OPTION B: Recreate Table (If Option A doesn't work)"
echo "⚠️  WARNING: This will delete all existing profile data!"
echo "1. Run the SQL in database/recreate_profiles_table.sql"
echo "2. This will recreate the table with proper structure"
echo "3. All existing profile data will be lost"
echo ""
echo "OPTION C: Manual Column Addition"
echo "1. Try adding the column manually:"
echo "   ALTER TABLE profiles ADD COLUMN has_performed_first_action BOOLEAN DEFAULT false;"
echo "2. If that fails, the table structure is corrupted"
echo ""
echo "🎯 RECOMMENDED APPROACH:"
echo "1. First try refreshing the schema cache"
echo "2. If that doesn't work, recreate the table"
echo "3. Test the first action tracking after fixing"
echo ""
echo "Press Enter to continue..."
read -r

echo "✅ Follow the steps above to fix the profiles table issue."
echo "The schema cache error should be resolved after proper table recreation."
