#!/bin/bash

echo "=== Fixing Edge Function Errors After Table Drop ==="
echo ""
echo "🚨 ERROR: Edge function returned a non-2xx status code"
echo ""
echo "This happens when edge functions try to access the profiles table"
echo "that was just dropped. Here's how to fix it:"
echo ""
echo "🔧 STEP 1: RECREATE THE PROFILES TABLE"
echo "1. Go to Supabase SQL Editor"
echo "2. Run the SQL in database/fix_edge_function_errors.sql"
echo "3. This will recreate the table with proper structure and policies"
echo ""
echo "🔧 STEP 2: RESTART EDGE FUNCTIONS"
echo "1. Go to Supabase Dashboard"
echo "2. Navigate to Edge Functions"
echo "3. Restart any edge functions that might be running"
echo "4. Or wait a few minutes for them to refresh automatically"
echo ""
echo "🔧 STEP 3: TEST THE FIX"
echo "1. Try the action that was causing the edge function error"
echo "2. Check if the first action tracking works now"
echo "3. Verify that profiles are being created properly"
echo ""
echo "📋 WHAT THE FIX DOES:"
echo "- Recreates profiles table with proper structure"
echo "- Adds all necessary RLS policies"
echo "- Recreates the trigger for automatic profile creation"
echo "- Adds proper indexes and comments"
echo "- Includes ON CONFLICT handling to prevent duplicate errors"
echo ""
echo "⚠️  IMPORTANT NOTES:"
echo "- All existing profile data was lost when you dropped the table"
echo "- New profiles will be created automatically when users sign up"
echo "- Edge functions should work properly after table recreation"
echo ""
echo "Press Enter to continue..."
read -r

echo "✅ Run the SQL script to recreate the profiles table and fix the edge function errors."
