#!/bin/bash

echo "=== Fixing user_id Null Values ==="
echo ""
echo "🔧 The error means there are existing rows where user_id is null."
echo "We need to populate those null values first."
echo ""
echo "📋 STEP-BY-STEP FIX:"
echo ""
echo "1. First, populate null user_id values:"
echo "   UPDATE profiles SET user_id = id WHERE user_id IS NULL;"
echo ""
echo "2. Then make user_id the primary key:"
echo "   ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_pkey;"
echo "   ALTER TABLE profiles ADD PRIMARY KEY (user_id);"
echo ""
echo "3. Make id column nullable:"
echo "   ALTER TABLE profiles ALTER COLUMN id DROP NOT NULL;"
echo ""
echo "🚀 OR run the complete fix:"
echo "Go to Supabase SQL Editor and run the SQL in database/fix_user_id_nulls.sql"
echo ""
echo "This will:"
echo "✅ Update any null user_id values to match the id"
echo "✅ Make user_id the primary key"
echo "✅ Make id column nullable"
echo ""
echo "Press Enter to continue..."
read -r

echo "✅ Run the SQL to fix the user_id null values and make it the primary key."
