#!/bin/bash

echo "=== Fixing create-guest Edge Function Error ==="
echo ""
echo "🚨 ERROR: Could not find the 'is_guest' column of 'profiles' in the schema cache"
echo ""
echo "The create-guest edge function is trying to insert these columns:"
echo "- user_id (UUID)"
echo "- handle (TEXT)"
echo "- is_guest (BOOLEAN)"
echo "- avatar_url (TEXT)"
echo ""
echo "But our profiles table doesn't have the 'is_guest' and 'user_id' columns."
echo ""
echo "🔧 SOLUTION:"
echo "1. Go to Supabase SQL Editor"
echo "2. Run the SQL in database/fix_create_guest_edge_function.sql"
echo "3. This will recreate the profiles table with the correct structure"
echo ""
echo "📋 WHAT THE FIX DOES:"
echo "- Adds 'user_id' column (for edge function compatibility)"
echo "- Adds 'is_guest' column (for edge function compatibility)"
echo "- Keeps all existing columns (id, email, display_name, handle, etc.)"
echo "- Updates RLS policies to work with both id and user_id"
echo "- Updates the trigger function to handle both columns"
echo "- Adds proper indexes for performance"
echo ""
echo "⚠️  IMPORTANT:"
echo "- This will drop and recreate the profiles table"
echo "- All existing profile data will be lost"
echo "- New profiles will be created automatically"
echo "- The create-guest edge function will work after this"
echo ""
echo "Press Enter to continue..."
read -r

echo "✅ Run the SQL script to fix the create-guest edge function error."
