#!/bin/bash

echo "=== First User Actions Analysis ==="
echo ""
echo "Based on the code analysis, here are ALL the actions that can trigger"
echo "the first point popup (when hasPerformedFirstAction = false):"
echo ""
echo "🎯 ACTIONS THAT TRIGGER FIRST POINT POPUP:"
echo ""
echo "1. ✅ First Post (5 points)"
echo "   - Triggered by: onFirstPost() in posts.service.ts"
echo "   - Reason: 'first_post'"
echo "   - Points: 5"
echo "   - One-time only: Yes (grantOnce)"
echo ""
echo "2. ✅ First Comment (5 points)"
echo "   - Triggered by: onFirstComment() in comments.service.ts"
echo "   - Reason: 'first_comment'"
echo "   - Points: 5"
echo "   - One-time only: Yes (grantOnce)"
echo ""
echo "3. ✅ First Like (1 point)"
echo "   - Triggered by: onFirstLike() in likes.service.ts"
echo "   - Reason: 'first_like'"
echo "   - Points: 1"
echo "   - One-time only: Yes (grantOnce)"
echo ""
echo "4. ✅ First Routine Task (1 point + 5 bonus = 6 total)"
echo "   - Triggered by: completeRoutineTask() in rewardsStore.ts"
echo "   - Reason: 'daily_routine_task'"
echo "   - Points: 1 (plus 5 bonus for first routine step)"
echo "   - One-time only: Bonus is one-time, task points are daily"
echo ""
echo "5. ✅ Daily Check-in (1 point)"
echo "   - Triggered by: checkIn() in rewardsStore.ts"
echo "   - Reason: 'daily_check_in'"
echo "   - Points: 1"
echo "   - One-time only: No (daily)"
echo ""
echo "6. ✅ Start Routine (5 points)"
echo "   - Triggered by: grantOnce('startedRoutine', 5, 'start_routine')"
echo "   - Reason: 'start_routine'"
echo "   - Points: 5"
echo "   - One-time only: Yes (grantOnce)"
echo ""
echo "7. ✅ Write Review (5 points)"
echo "   - Triggered by: earn(5, 'write_review')"
echo "   - Reason: 'write_review'"
echo "   - Points: 5"
echo "   - One-time only: No (can write multiple reviews)"
echo ""
echo "8. ✅ Refer Friend (20 points)"
echo "   - Triggered by: addReferral() in rewardsStore.ts"
echo "   - Reason: 'refer_friend'"
echo "   - Points: 20"
echo "   - One-time only: No (up to 20 referrals)"
echo ""
echo "❌ ACTIONS THAT DO NOT TRIGGER FIRST POINT POPUP:"
echo ""
echo "1. ❌ Signup Bonus (250 points)"
echo "   - Reason: 'Sign up bonus'"
echo "   - Excluded by: reason !== 'Sign up bonus'"
echo ""
echo "2. ❌ Post Engagement Rewards"
echo "   - Reason: 'post_engagement_likes' or 'post_engagement_comments'"
echo "   - These are ongoing rewards, not first actions"
echo ""
echo "3. ❌ Purchase Rewards"
echo "   - Reason: 'purchase'"
echo "   - These are ongoing rewards, not first actions"
echo ""
echo "4. ❌ Redeem Actions"
echo "   - Reason: 'redeem'"
echo "   - These are point deductions, not earnings"
echo ""
echo "Press Enter to continue..."
read -r

echo "🧪 TEST SCENARIOS:"
echo ""
echo "Scenario 1 - New user's first post:"
echo "  - hasPerformedFirstAction = false"
echo "  - onFirstPost() called"
echo "  - grantOnce('firstPost', 5, 'first_post')"
echo "  - earn(5, 'first_post') called"
echo "  - isFirstUserAction = true (reason !== 'Sign up bonus')"
echo "  - ✅ FIRST POINT POPUP SHOWS"
echo ""
echo "Scenario 2 - New user's first like:"
echo "  - hasPerformedFirstAction = false"
echo "  - onFirstLike() called"
echo "  - grantOnce('firstLike', 1, 'first_like')"
echo "  - earn(1, 'first_like') called"
echo "  - isFirstUserAction = true"
echo "  - ✅ FIRST POINT POPUP SHOWS"
echo ""
echo "Scenario 3 - New user's first comment:"
echo "  - hasPerformedFirstAction = false"
echo "  - onFirstComment() called"
echo "  - grantOnce('firstComment', 5, 'first_comment')"
echo "  - earn(5, 'first_comment') called"
echo "  - isFirstUserAction = true"
echo "  - ✅ FIRST POINT POPUP SHOWS"
echo ""
echo "Press Enter to continue..."
read -r

echo "✅ CONCLUSION:"
echo ""
echo "YES! First user actions DO include:"
echo "- ✅ First post (5 points)"
echo "- ✅ First like (1 point)"
echo "- ✅ First comment (5 points)"
echo "- ✅ First routine task (1 point + 5 bonus)"
echo "- ✅ Daily check-in (1 point)"
echo "- ✅ Start routine (5 points)"
echo "- ✅ Write review (5 points)"
echo "- ✅ Refer friend (20 points)"
echo ""
echo "The first point popup will show for ANY of these actions when"
echo "hasPerformedFirstAction = false, regardless of which one the user"
echo "does first. Once any of these actions is performed, the popup"
echo "will never show again for that user."
