#!/bin/bash

echo "=== Testing Bonus Ledger Entries ==="
echo ""
echo "This test will verify that bonuses are properly added to the ledger."
echo ""
echo "Expected ledger entries:"
echo "1. Signup bonus: 250 points (reason: 'Sign up bonus')"
echo "2. First routine step bonus: 5 points (reason: 'first_routine_step_bonus')"
echo "3. First routine task: 1 point (reason: 'daily_routine_task')"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Create a new user account (or reset existing)"
echo "2. Complete your very first routine step"
echo "3. Go to Rewards page and check the ledger"
echo ""
echo "You should see:"
echo "- 250 point signup bonus entry"
echo "- 5 point first routine step bonus entry" 
echo "- 1 point daily routine task entry"
echo ""
echo "Total should be 256 points (250 + 5 + 1)"
echo ""
echo "If any bonuses are missing from the ledger, there's a bug in the grantOnce function."
echo ""
echo "Press Enter when you've completed the test..."
read -r

echo "Test completed. Please report any missing ledger entries."
